# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Display & Cell Pros Core"
handle = "displaycellpros"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
client_id = "88dda1b26f28d64c58165be9bc988b2c"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[pos]
embedded = false

[app_proxy]
url = "https://ais-pre-jaxozcgj5xjwxv2xfpcms5-367327296310.us-west2.run.app"
subpath = "apps"
prefix = "apps"
